version: "3"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: inflight
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

  node:
    build:
      context: .
      args:
        - NODE_ENV=production
    working_dir: /opt/inflight-assignment
    ports:
      - 5000:5000
      - 3000:3000
    depends_on:
      - mongo

volumes:
  mongodb:
  mongodb_config:
