version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: inflight
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

  node:
    build:
      context: .
      args:
        - NODE_ENV=development
    working_dir: /opt/inflight-assignment
    ports:
      - 80:5000
    depends_on:
      - mongo

volumes:
  mongodb:
  mongodb_config: