const FlightDetailsActionTypes = {
  FETCH_FLIGHT_DETAILS_START: "FETCH_FLIGHT_DETAILS_START",
  FETCH_FLIGHT_DETAILS_SUCCESS: "FETCH_FLIGHT_DETAILS_SUCCESS",
  FETCH_FLIGHT_DETAILS_ERROR: "FETCH_FLIGHT_DETAILS_ERROR"
};

export default FlightDetailsActionTypes;
