const FlightDetailsActionTypes = {
  FETCH_FLIGHT_DETAILS_START: "FETCH_FLIGHT_DETAILS_START",
  FETCH_FLIGHT_DETAILS_SUCCESS: "FETCH_FLIGHT_DETAILS_SUCCESS",

  FETCH_FLIGHT_STATUS_START: "FETCH_FLIGHT_STATUS_START",
  FETCH_FLIGHT_STATUS_SUCCESS: "FETCH_FLIGHT_STATUS_SUCCESS",

  UPDATE_FLIGHT_STATUS_START: "UPDATE_FLIGHT_STATUS_START",
  UPDATE_FLIGHT_STATUS_SUCCESS: "UPDATE_FLIGHT_STATUS_SUCCESS",

  DELETE_FLIGHT_STATUS_START: "DELETE_FLIGHT_STATUS_START",
  DELETE_FLIGHT_STATUS_SUCCESS: "DELETE_FLIGHT_STATUS_SUCCESS",

  ASYNC_OPERATION_FLIGHT_STATUS_FAILURE: "ASYNC_OPERATION_FLIGHT_STATUS_FAILURE"
};

export default FlightDetailsActionTypes;
