const FlightDetailsActionTypes = {
  FETCH_FLIGHT_DETAILS_START: "FETCH_FLIGHT_DETAILS_START",
  FETCH_FLIGHT_DETAILS_SUCCESS: "FETCH_FLIGHT_DETAILS_SUCCESS",
  FETCH_FLIGHT_STATUS_START: "FETCH_FLIGHT_STATUS_START",
  FETCH_FLIGHT_STATUS_SUCCESS: "FETCH_FLIGHT_STATUS_SUCCESS",
  FETCH_FAILURE: "FETCH_FAILURE"
};

export default FlightDetailsActionTypes;
